// app/api/employees/[id]/reset-password/route.js
//
// ✅ NEW: Admin kisi bhi employee ka password reset kar sakta hai
//
// Flow:
//   1. Admin employee ka ID pass karta hai
//   2. Option 1: Auto-generate karo (name+phone formula)
//   3. Option 2: Custom password set karo
//   4. Response mein naya plain password ek baar dikhao
//
// Security:
//   - verifyAdmin middleware — sirf admin access kar sakta hai
//   - Naya password response mein sirf ek baar aata hai — DB mein plain nahi

import { connectDB }  from "@/lib/db";
import Employee       from "@/app/api/employees/models/Employee";
import { verifyAdmin } from "@/app/api/middleware/auth";
import bcrypt         from "bcryptjs";

// Auto-generate password: name first 3 + phone last 4
const generatePassword = (name, phone) => {
  const namePart  = name.trim().replace(/\s+/g, "").substring(0, 3).toUpperCase();
  const phonePart = String(phone).replace(/\D/g, "").slice(-4);
  return `${namePart}${phonePart}`;
};

export const PATCH = verifyAdmin(async (req, context) => {
  try {
    await connectDB();

    const { id } = await context.params;

    // customPassword optional — nahi diya toh auto-generate
    const { customPassword } = await req.json().catch(() => ({}));

    // ── Employee fetch ────────────────────────────────────────────
    const emp = await Employee.findById(id);
    if (!emp) {
      return Response.json(
        { success: false, error: "Employee nahi mila" },
        { status: 404 }
      );
    }

    // ── Generate / validate new password ─────────────────────────
    let newPlainPassword;

    if (customPassword) {
      // Custom password diya hai
      if (String(customPassword).length < 6) {
        return Response.json(
          { success: false, error: "Password kam se kam 6 characters ka hona chahiye" },
          { status: 400 }
        );
      }
      newPlainPassword = String(customPassword).trim();
    } else {
      // Auto-generate: default formula
      newPlainPassword = generatePassword(emp.name, emp.phone);
    }

    // ── Hash and save ─────────────────────────────────────────────
    const hashed  = await bcrypt.hash(newPlainPassword, await bcrypt.genSalt(10));
    emp.password  = hashed;
    await emp.save();

    return Response.json({
      success: true,
      message: `${emp.name} ka password reset ho gaya`,
      data: {
        empId:        emp.empId,
        name:         emp.name,
        phone:        emp.phone,
        // Sirf ek baar dikhao — DB mein plain save nahi hota
        newPassword:  newPlainPassword,
        loginNote:    `Phone: ${emp.phone} | Password: ${newPlainPassword}`,
        isAutoGenerated: !customPassword,
      },
    }, { status: 200 });

  } catch (err) {
    console.error("Reset password error:", err);
    return Response.json(
      { success: false, error: err.message },
      { status: 500 }
    );
  }
});